create table if not exists kos_entries (
  id bigint generated by default as identity primary key,
  kamar integer not null,
  nama text not null,
  bulan text not null,
  jumlah integer not null default 300000,
  tanggal date not null default current_date,
  periode text not null,
  created_at timestamptz not null default now()
);

create table if not exists token_entries (
  id bigint generated by default as identity primary key,
  kamar integer not null,
  nama text not null,
  jumlah integer not null,
  nomor_token text,
  tanggal date not null default current_date,
  periode text not null,
  created_at timestamptz not null default now()
);

alter table kos_entries enable row level security;
alter table token_entries enable row level security;

drop policy if exists "public read kos" on kos_entries;
drop policy if exists "public insert kos" on kos_entries;
drop policy if exists "authenticated read kos" on kos_entries;
drop policy if exists "authenticated insert kos" on kos_entries;
drop policy if exists "public read token" on token_entries;
drop policy if exists "public insert token" on token_entries;
drop policy if exists "authenticated read token" on token_entries;
drop policy if exists "authenticated insert token" on token_entries;

create policy "authenticated read kos" on kos_entries for select to authenticated using (true);
create policy "authenticated insert kos" on kos_entries for insert to authenticated with check (true);

create policy "authenticated read token" on token_entries for select to authenticated using (true);
create policy "authenticated insert token" on token_entries for insert to authenticated with check (true);
